name: Gerar APK Automático

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Instalar Java e Ferramentas Android
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar Bubblewrap CLI
        run: npm install -g @bubblewrap/cli

      - name: Gerar TWA sem interatividade
        run: |
          npx @bubblewrap/cli init --manifest=https://digaooliver92-hue.github.io/midia-indoor-player/manifest.json --directory=android-app --skip=androidManifestValidation --defaults

      - name: Compilar APK
        run: |
          cd android-app && npm run build

      - name: Salvar APK Gerado
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: android-app/app/build/outputs/apk/release/*.apk
