name: Gerar APK Automático

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar Bubblewrap CLI
        run: npm install -g @bubblewrap/cli

      - name: Inicializar Projeto PWA
        run: |
          bubblewrap init --manifest=https://digaooliver92-hue.github.io/midia-indoor-player/manifest.json --skip=androidManifestValidation

      - name: Compilar APK
        run: |
          bubblewrap build

      - name: Salvar APK Gerado
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: |
            *.apk
            app/build/outputs/apk/release/*.apk
